knp_snappy:
    pdf:
        enabled: true
        binary: wkhtmltopdf
        options:
            enable-local-file-access: true
            margin-top: 8
            margin-right: 8
            margin-bottom: 8
            margin-left: 8
    image:
        enabled: false
