parameters:
<<<<<<< HEAD
    openweather_api_key: '%env(OPENWEATHER_API_KEY)%'
    openai_api_key: '%env(OPENAI_API_KEY)%'
    openai_model: '%env(OPENAI_MODEL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\WeatherService:
        arguments:
            $openWeatherApiKey: '%openweather_api_key%'

    App\Service\AiWasteAnalyzerService:
        arguments:
            $openAiApiKey: '%openai_api_key%'
            $openAiModel: '%openai_model%'
=======
    face_upload_dir: '%kernel.project_dir%/public/uploads/faces'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    python_face_service_url: 'http://localhost:5000'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Service\AiRecommendationService:
    bind:
      $openAiApiKey: "%env(OPENAI_API_KEY)%"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Service\GroqAnalyzer:
    arguments:
      $groqApiKey: "%env(GROQ_API_KEY)%"

  App\Service\GroqReportService:
    arguments:
      $groqApiKey: "%env(GROQ_API_KEY)%"

  # Service météorologique
  App\Service\WeatherServices:
    arguments:
      $openWeatherApiKey: "%env(OPENWEATHER_API_KEY)%"

  # Service de prédiction
  App\Service\PredictionService: ~

  App\Service\FaceRecognitionService:
    arguments:
      $pythonFaceServiceUrl: "%python_face_service_url%"
>>>>>>> 163f23d3ff1ed003948dbcee8c3696b66c6027ca
