parameters:
    face_upload_dir: '%kernel.project_dir%/public/uploads/faces'
    python_face_service_url: 'http://localhost:5000'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\FaceRecognitionService:
        arguments:
            $uploadDir: '%face_upload_dir%'
            $pythonServiceUrl: '%python_face_service_url%'

    App\Service\WeatherService:
        arguments:
            $apiKey: '%env(API_NINJAS_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'